export const FETCH_USER_OFFERS_BEGIN = "FETCH_USER_OFFERS_BEGIN";
export const FETCH_USER_OFFERS_SUCCESS = "FETCH_USER_OFFERS_SUCCESS";
export const FETCH_USER_OFFERS_FAILED = "FETCH_USER_OFFERS_FAILED";

export const FETCH_OFFER_BEGIN = "FETCH_OFFER_BEGIN";
export const FETCH_OFFER_SUCCESS = "FETCH_OFFER_SUCCESS";
export const FETCH_OFFER_FAILED = "FETCH_OFFER_FAILED";

export const FETCH_OFFER_RIDES_BEGIN = "FETCH_OFFER_RIDES_BEGIN";
export const FETCH_OFFER_RIDES_SUCCESS = "FETCH_OFFER_RIDES_SUCCESS";
export const FETCH_OFFER_RIDES_FAILED = "FETCH_OFFER_RIDES_FAILED";

export const CREATE_OFFER_BEGIN = "CREATE_OFFER_BEGIN";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAILED = "CREATE_OFFER_FAILED";

export const UPDATE_OFFER_BEGIN = "UPDATE_OFFER_BEGIN";
export const UPDATE_OFFER_SUCCESS = "UPDATE_OFFER_SUCCESS";
export const UPDATE_OFFER_FAILED = "UPDATE_OFFER_FAILED";

export const DELETE_OFFER_BEGIN = "DELETE_OFFER_BEGIN";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAILED = "DELETE_OFFER_FAILED";

export const SEARCH_OFFERS_BEGIN = "SEARCH_OFFERS_BEGIN";
export const SEARCH_OFFERS_SUCCESS = "SEARCH_OFFERS_SUCCESS";
export const SEARCH_OFFERS_FAILED = "SEARCH_OFFERS_FAILED";
