export const FETCH_USER_RIDES_BEGIN = "FETCH_USER_RIDES_BEGIN";
export const FETCH_USER_RIDES_SUCCESS = "FETCH_USER_RIDES_SUCCESS";
export const FETCH_USER_RIDES_FAILED = "FETCH_USER_RIDES_FAILED";

export const FETCH_RIDE_BEGIN = "FETCH_RIDE_BEGIN";
export const FETCH_RIDE_SUCCESS = "FETCH_RIDE_SUCCESS";
export const FETCH_RIDE_FAILED = "FETCH_RIDE_FAILED";

export const REQUEST_RIDE_BEGIN = "REQUEST_RIDE_BEGIN";
export const REQUEST_RIDE_SUCCESS = "REQUEST_RIDE_SUCCESS";
export const REQUEST_RIDE_FAILED = "REQUEST_RIDE_FAILED";

export const UPDATE_RIDE_BEGIN = "UPDATE_RIDE_BEGIN";
export const UPDATE_RIDE_SUCCESS = "UPDATE_RIDE_SUCCESS";
export const UPDATE_RIDE_FAILED = "UPDATE_RIDE_FAILED";

export const CANCEL_RIDE_BEGIN = "CANCEL_RIDE_BEGIN";
export const CANCEL_RIDE_SUCCESS = "CANCEL_RIDE_SUCCESS";
export const CANCEL_RIDE_FAILED = "CANCEL_RIDE_FAILED";

export const ACCEPT_OR_REJECT_RIDE_BEGIN = "ACCEPT_OR_REJECT_RIDE_BEGIN";
export const ACCEPT_OR_REJECT_RIDE_SUCCESS = "ACCEPT_OR_REJECT_RIDE_SUCCESS";
export const ACCEPT_OR_REJECT_RIDE_FAILED = "ACCEPT_OR_REJECT_RIDE_FAILED";
