export const LOGIN_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_FAILED = "LOGIN_USER_FAILED";
export const LOGOUT = "LOGOUT_USER";

export const SIGNUP_BEGIN = "ADD_USER_BEGIN";
export const SIGNUP_SUCCESS = "ADD_USER_SUCCESS";
export const SIGNUP_FAILED = "ADD_USER_FAILED";

export const ADD_VEHICLE_BEGIN = "ADD_VEHICLE_BEGIN";
export const ADD_VEHICLE_SUCCESS = "ADD_VEHICLE_SUCCESS";
export const ADD_VEHICLE_FAILED = "ADD_VEHICLE_FAILED";

export const UPDATE_VEHICLE_BEGIN = "UPDATE_VEHICLE_BEGIN";
export const UPDATE_VEHICLE_SUCCESS = "UPDATE_VEHICLE_SUCCESS";
export const UPDATE_VEHICLE_FAILED = "UPDATE_VEHICLE_FAILED";

export const DELETE_VEHICLE_BEGIN = "DELETE_VEHICLE_BEGIN";
export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";
export const DELETE_VEHICLE_FAILED = "DELETE_VEHICLE_FAILED";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

export const CLOSE_ERROR = "CLOSE_ERROR_POPUP";
export const CLOSE_RESPONSE = "CLOSE_RESPONSE_POPUP";
